version: '3.9'
services:
    influxdb:
        image: influxdb
        container_name: influxdb4jmeter
        ports:
            - 8086:8086
        volumes:
            - influxdb4jmeter:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=db0
            - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

    grafana:
        image: grafana/grafana
        container_name: grafana4jmeter
        ports:
            - 3000:3000
        volumes:
            - grafana4jmeter:/var/lib/grafana
        depends_on:
            - influxdb
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

volumes:
    grafana4jmeter:
        external: true
    influxdb4jmeter:
        external: true
