version: '3.9'
services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - 9090:9090
        volumes:
            - prometheus:/etc/prometheus
        hostname: prometheus
        extra_hosts:
            - "host.docker.internal:host-gateway"
        user: root
    alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        ports:
            - 9093:9093
            - 5001:5001
        volumes:
            - alertmanager:/etc/alertmanager
        hostname: alertmanager
        extra_hosts:
            - "host.docker.internal:host-gateway"
    node-exporter:
        image: prom/node-exporter
        container_name: node-exporter
        hostname: node_exporter
        ports:
            - 9100:9100
volumes:
    prometheus:
        external: true
    alertmanager:
        external: true