
version: '3.9'
services:
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - postgres_initd:/docker-entrypoint-initdb.d
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
        hostname: postgres
        user: root

    pgadmin4:
        image: dpage/pgadmin4
        container_name: pgadmin4
        ports:
            - 5050:80
        volumes:
            - pgadmin4_data:/var/lib/pgadmin
        environment:
            PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
            PGADMIN_DEFAULT_EMAIL: do030b@gmail.com
            PGADMIN_DEFAULT_PASSWORD: pgadmin
        hostname: pgadmin4
        depends_on:
          - postgres

volumes:
    postgres_initd:
        external: true
    postgres_data:
        external: true
    pgadmin4_data:
        external: true